name: Aktualizuj zestawy z Rebrickable

on:
  workflow_dispatch:
  schedule:
    # 01:30 UTC (w Polsce zwykle noc)
    - cron: "30 1 * * *"

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install requests

      - name: Fetch from Rebrickable
        env:
          REBRICKABLE_KEY: ${{ secrets.REBRICKABLE_KEY }}
          REBRICKABLE_USER_TOKEN: ${{ secrets.REBRICKABLE_USER_TOKEN }}
        run: python scripts/fetch_rebrickable.py

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/data/sets.json
          git commit -m "Update Rebrickable sets" || echo "No changes"
          git push
